# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-25 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyproperty',
            name='property_image1',
            field=models.ImageField(blank=True, upload_to='buyproperties'),
        ),
        migrations.AddField(
            model_name='buyproperty',
            name='property_image2',
            field=models.ImageField(blank=True, upload_to='buyproperties'),
        ),
        migrations.AddField(
            model_name='buyproperty',
            name='property_image3',
            field=models.ImageField(blank=True, upload_to='buyproperties'),
        ),
        migrations.AddField(
            model_name='buyproperty',
            name='property_image4',
            field=models.ImageField(blank=True, upload_to='buyproperties'),
        ),
        migrations.AddField(
            model_name='buyproperty',
            name='property_image5',
            field=models.ImageField(blank=True, upload_to='buyproperties'),
        ),
        migrations.AddField(
            model_name='buyproperty',
            name='property_image6',
            field=models.ImageField(blank=True, upload_to='buyproperties'),
        ),
        migrations.AddField(
            model_name='buyproperty',
            name='property_image7',
            field=models.ImageField(blank=True, upload_to='buyproperties'),
        ),
        migrations.AddField(
            model_name='buyproperty',
            name='property_image8',
            field=models.ImageField(blank=True, upload_to='buyproperties'),
        ),
        migrations.AddField(
            model_name='buyproperty',
            name='property_image9',
            field=models.ImageField(blank=True, upload_to='buyproperties'),
        ),
    ]
